-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4GHqcssw99j3ROSL
U9sVEjUID9bzfqn1NYhNVC0tnYygCgYIKoZIzj0DAQehRANCAAQMpy00qbYuQzn2
OroZWdnxTAZjOA0JX+oPPJVSGXIH3g/GlZauJYGaDtyG6gvFdQEHjvtKEmoyhE9r
8vr07ez5
-----END PRIVATE KEY-----